title: Lijst van kleurvariabelen
hero_image: images/banner.png
description: Lijst met kleurvariabelen
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Lijst van kleurvariabelen
