title: Ambient art colour palette
hero_image: images/banner.png
description: Ambient art colour palette
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Ambient art colour palette
