---
title: Liste over fargevariabler
hero_image: images/banner.png
description: Liste over fargevariabler
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Liste over fargevariabler
