---
title: Liste over farvevariabler
hero_image: images/banner.png
description: Liste over farvevariabler
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Liste over farvevariabler
