---
title: Lista de variáveis de cores
hero_image: images/banner.png
description: Lista de variáveis de cores
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Lista de variáveis de cores
