---
title: Luettelo värimuuttujista
hero_image: images/banner.png
description: Luettelo värimuuttujista
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Luettelo värimuuttujista
