title: Lista de variables de color
hero_image: images/banner.png
description: Lista de variables de color
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Lista de variables de color
