---
title: Lista variabilelor de culoare
hero_image: images/banner.png
description: Lista variabilelor de culoare
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Lista variabilelor de culoare
