---
title: Seznam barvnih spremenljivk
hero_image: images/banner.png
description: Seznam barvnih spremenljivk
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Seznam barvnih spremenljivk
