title: Seznam proměnných s barvami
hero_image: images/banner.png
description: Seznam proměnných s barvami
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Seznam proměnných s barvami
