title: Lista zmiennych kolorów
hero_image: images/banner.png
description: Lista zmiennych kolorów
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Lista zmiennych kolorów
