title: Zoznam farebných premenných
hero_image: images/banner.png
description: Zoznam farebných premenných
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Zoznam farebných premenných
