title: Elenco delle variabili di colore
hero_image: images/banner.png
description: Elenco delle variabili di colore
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Elenco delle variabili di colore
